substitutions:
  name: "seeedstudio-mr60bha2-kit"
  friendly_name: "Seeed Studio MR60BHA2 Kit"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "JtGIRzGrFsSK9sy1zO8ZrgfExySLbj4m6nzb0aM5dCY="

ota:
  - platform: esphome
    password: "29f6e64a04f59e7a364acdb44d0d12d4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mr60Bha2 Fallback Hotspot"
    password: "88dTBvid12bU"

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/limengdu/MR60BHA2_ESPHome_external_components
      ref: main
    components: [ seeed_mr60bha2 ]
    refresh: 0s

light:
  - platform: esp32_rmt_led_strip
    id: led_ring
    name: "Seeed MR60BHA2 RGB Light"
    pin: GPIO1
    num_leds: 1
    rgb_order: GRB
    chipset: ws2812

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true
  id: bus_a

uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: 17
  tx_pin: 16
  parity: NONE
  stop_bits: 1

seeed_mr60bha2:
  id: my_seeed_mr60bha2

binary_sensor:
  - platform: seeed_mr60bha2
    has_target:
      name: "Person Information"

sensor:
  - platform: bh1750
    name: "Seeed MR60BHA2 Illuminance"
    address: 0x23
    update_interval: 1s
  - platform: seeed_mr60bha2
    breath_rate:
      name: "Real-time respiratory rate"
    heart_rate:
      name: "Real-time heart rate"
    distance:
      name: "Distance to detection object"
    num_targets:
      name: "Target Number"
    