substitutions:
  name: "xiao-esp32-c6-led-button"
  friendly_name: "XIAO ESP32-C3 MP3 Player"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ufuQUoykzlE1qQDM3AugjTFpb3fH6h27lP2QhyzS0Zo="

  # Services for Home Assistant integration
  services:
    # Play specific track by index
    - service: play_track
      variables:
        track: int
      then:
        - lambda: |-
            char cmd[64];
            snprintf(cmd, sizeof(cmd), "AT+LPLAY=sd0:/%04d.mp3\r\n", track);
            id(mp3_uart).write_str(cmd);
            id(current_track) = track;
            id(mp3_track).publish_state(track);
            ESP_LOGD("MP3", "Service: Play track %d", track);
    
    # Play song by filename
    - service: play_file
      variables:
        filename: string
      then:
        - lambda: |-
            std::string cmd = "AT+LPLAY=sd0:/" + filename + "\r\n";
            id(mp3_uart).write_str(cmd.c_str());
            ESP_LOGD("MP3", "Service: Play file %s", filename.c_str());
    
    # Play song from directory
    - service: play_directory_song
      variables:
        directory: string
        index: int
      then:
        - lambda: |-
            char cmd[128];
            snprintf(cmd, sizeof(cmd), "AT+LPLAY=sd0:/%s/%04d.mp3\r\n", directory.c_str(), index);
            id(mp3_uart).write_str(cmd);
            ESP_LOGD("MP3", "Service: Play %s/%04d.mp3", directory.c_str(), index);
    
    # Set volume
    - service: set_volume
      variables:
        volume: int
      then:
        - lambda: |-
            if (volume >= 0 && volume <= 31) {
              char cmd[32];
              snprintf(cmd, sizeof(cmd), "AT+VOL=%d\r\n", volume);
              id(mp3_uart).write_str(cmd);
              id(current_volume) = volume;
              id(mp3_volume).publish_state(volume);
              ESP_LOGD("MP3", "Service: Set volume to %d", volume);
            }
    
    # Pause or play
    - service: pause_play
      then:
        - lambda: |-
            id(mp3_uart).write_str("AT+PP\r\n");
            ESP_LOGD("MP3", "Service: Pause/Play");
    
    # Stop playback
    - service: stop
      then:
        - lambda: |-
            id(mp3_uart).write_str("AT+STOP\r\n");
            ESP_LOGD("MP3", "Service: Stop");
    
    # Next track
    - service: next
      then:
        - lambda: |-
            id(mp3_uart).write_str("AT+NEXT\r\n");
            id(current_track) = id(current_track) + 1;
            id(mp3_track).publish_state(id(current_track));
            ESP_LOGD("MP3", "Service: Next");
    
    # Previous track
    - service: previous
      then:
        - lambda: |-
            id(mp3_uart).write_str("AT+PREV\r\n");
            if (id(current_track) > 1) {
              id(current_track) = id(current_track) - 1;
            }
            id(mp3_track).publish_state(id(current_track));
            ESP_LOGD("MP3", "Service: Previous");
    
    # Send custom AT command
    - service: send_command
      variables:
        command: string
      then:
        - lambda: |-
            std::string cmd = command + "\r\n";
            id(mp3_uart).write_str(cmd.c_str());
            ESP_LOGD("MP3", "Service: Send command: %s", command.c_str());

ota:
  - platform: esphome
    password: "e9f559ab8b774395e5fe2a5a173706de"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xiao-Esp32-C3-Mp3"
    password: "llsJn46TfWUB"

captive_portal:
    

# UART configuration for WT2605C module
# RX=D7 (GPIO7), TX=D6 (GPIO6)
uart:
  id: mp3_uart
  tx_pin: GPIO21  # D6
  rx_pin: GPIO20  # D7
  baud_rate: 115200

# Global variables to store state
globals:
  - id: current_volume
    type: int
    restore_value: yes
    initial_value: '15'
  
  - id: current_track
    type: int
    restore_value: yes
    initial_value: '1'

# Number component for volume control (0-31)
number:
  - platform: template
    name: "Volume"
    id: mp3_volume
    min_value: 0
    max_value: 31
    step: 1
    initial_value: 15
    optimistic: true
    set_action:
      - lambda: |-
          char cmd[32];
          snprintf(cmd, sizeof(cmd), "AT+VOL=%d\r\n", (int)x);
          id(mp3_uart).write_str(cmd);
          id(current_volume) = (int)x;
          ESP_LOGD("MP3", "Set volume to: %d", (int)x);
  - platform: template
    name: "Track Number"
    id: mp3_track
    min_value: 1
    max_value: 9999
    step: 1
    initial_value: 1
    optimistic: true
    set_action:
      - lambda: |-
          char cmd[64];
          snprintf(cmd, sizeof(cmd), "AT+LPLAY=sd0:/%04d.mp3\r\n", (int)x);
          id(mp3_uart).write_str(cmd);
          id(current_track) = (int)x;
          ESP_LOGD("MP3", "Play track: %d", (int)x);

# Select component for play mode
select:
  - platform: template
    name: "Play Mode"
    id: mp3_play_mode
    options:
      - "Loop"
      - "Single Loop"
      - "Folder Loop"
      - "Random"
      - "Single Shot"
    initial_option: "Loop"
    optimistic: true
    set_action:
      - lambda: |-
          int mode = 0;
          if (x == "Loop") mode = 0;
          else if (x == "Single Loop") mode = 1;
          else if (x == "Folder Loop") mode = 2;
          else if (x == "Random") mode = 3;
          else if (x == "Single Shot") mode = 4;
          
          char cmd[32];
          snprintf(cmd, sizeof(cmd), "AT+REPEATMODE=%d\r\n", mode);
          id(mp3_uart).write_str(cmd);
          ESP_LOGD("MP3", "Set play mode to: %s (%d)", x.c_str(), mode);

# Button components for playback control
button:
  - platform: template
    name: "Play"
    id: mp3_play
    icon: "mdi:play"
    on_press:
      - lambda: |-
          id(mp3_uart).write_str("AT+PP\r\n");
          ESP_LOGD("MP3", "Play/Pause toggled");
  
  - platform: template
    name: "Stop"
    id: mp3_stop
    icon: "mdi:stop"
    on_press:
      - lambda: |-
          id(mp3_uart).write_str("AT+STOP\r\n");
          ESP_LOGD("MP3", "Stop");
  
  - platform: template
    name: "Next"
    id: mp3_next
    icon: "mdi:skip-next"
    on_press:
      - lambda: |-
          id(mp3_uart).write_str("AT+NEXT\r\n");
          id(current_track) = id(current_track) + 1;
          ESP_LOGD("MP3", "Next track");
  
  - platform: template
    name: "Previous"
    id: mp3_previous
    icon: "mdi:skip-previous"
    on_press:
      - lambda: |-
          id(mp3_uart).write_str("AT+PREV\r\n");
          if (id(current_track) > 1) {
            id(current_track) = id(current_track) - 1;
          }
          ESP_LOGD("MP3", "Previous track");
  
  - platform: template
    name: "Volume Up"
    id: mp3_volume_up
    icon: "mdi:volume-plus"
    on_press:
      - lambda: |-
          id(mp3_uart).write_str("AT+VOLUP\r\n");
          if (id(current_volume) < 31) {
            id(current_volume) = id(current_volume) + 1;
            id(mp3_volume).publish_state(id(current_volume));
          }
          ESP_LOGD("MP3", "Volume up to: %d", id(current_volume));
  
  - platform: template
    name: "Volume Down"
    id: mp3_volume_down
    icon: "mdi:volume-minus"
    on_press:
      - lambda: |-
          id(mp3_uart).write_str("AT+VOLDOWN\r\n");
          if (id(current_volume) > 0) {
            id(current_volume) = id(current_volume) - 1;
            id(mp3_volume).publish_state(id(current_volume));
          }
          ESP_LOGD("MP3", "Volume down to: %d", id(current_volume));

# Text sensor to display current status
text_sensor:
  - platform: template
    name: "Current Track"
    id: current_track_display
    icon: "mdi:music-note"
    lambda: |-
      char buffer[32];
      snprintf(buffer, sizeof(buffer), "Track %d", id(current_track));
      return std::string(buffer);
    update_interval: 5s

# Optional: Add a switch for power control or enable/disable
switch:
  - platform: template
    name: "MP3 Player Enable"
    id: mp3_enable
    icon: "mdi:power"
    optimistic: true
    turn_on_action:
      - lambda: |-
          // Initialize MP3 player
          char cmd[32];
          snprintf(cmd, sizeof(cmd), "AT+VOL=%d\r\n", id(current_volume));
          id(mp3_uart).write_str(cmd);
          ESP_LOGD("MP3", "MP3 Player enabled");
    turn_off_action:
      - lambda: |-
          id(mp3_uart).write_str("AT+STOP\r\n");
          ESP_LOGD("MP3", "MP3 Player disabled");
