substitutions:
  name: "xiao-esp32-s3-camera"
  friendly_name: "XIAO ESP32-S3 Camera"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
    board_build.extra_flags:
    - "-DARDUINO_HW_CDC_ON_BOOT=0"

esp32:
  board: seeed_xiao_esp32s3
  variant: esp32s3
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz

logger:
  level: VERBOSE
  tx_buffer_size: 256

# Enable Home Assistant API
api:
  encryption:
    key: "k/QxEx306Vcg1PpiO9VXl+wOBKsVNlXVL/7y5A+FmTU="

ota:
  - platform: esphome
    password: "cfbe34b762b17c1e3e3e669f3a1452fe"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xiao-Esp Fallback Hotspot"
    password: "jIIBvJNnOz1V"

captive_portal:

# Example configuration entry
i2c:
  - id: camera_i2c
    sda: GPIO40
    scl: GPIO39
esp32_camera:
  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_id: camera_i2c
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13
  name: My Camera
  vertical_flip: true
  horizontal_flip: true
