substitutions:
  name: "xiao-esp32-c3-led-strip"
  friendly_name: "XIAO ESP32-C3 LED Strip"
  led_pin: GPIO2
  num_leds: 48

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "umKYyCZ7Jv3Xoek0DGG8uzD9WgVhk4vB2csvE+rl1Ow="

ota:
  - platform: esphome
    password: "c502f40344b19f27577e2ae9bdf652f4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xiao-Esp32-C3-Led-Strip"
    password: "SmB4Wkkg4tV9"

captive_portal:

light:
  - platform: neopixelbus
    name: ${friendly_name}
    id: ws2812_strip
    
    # --- Hardware Configuration ---
    variant: ws2812
    pin: ${led_pin}
    num_leds: ${num_leds}
    method: esp32_rmt
    
    # --- Default Behavior ---
    default_transition_length: 0.5s
    restore_mode: ALWAYS_ON

    # --- Effects List (Based on ESPHome Documentation) ---
    effects:
      # -------------------------------------------------
      # 1. Generic Effects (Compatible with all lights)
      # -------------------------------------------------
      - pulse:
          name: "Pulse"

      - strobe:
          name: "Strobe"
      - strobe:
          name: "Strobe Red and Blue"
          colors:
            - state: true
              red: 1.0
              green: 0.0
              blue: 0.0
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              red: 0.0
              green: 0.0
              blue: 1.0
              duration: 500ms
            - state: false
              duration: 250ms

      - random:
          name: "Random"
      - random:
          name: "Slow Random Transition"
          transition_length: 10s
          update_interval: 15s

      - flicker:
          name: "Flicker"

      # -------------------------------------------------
      # 2. Addressable Effects
      # -------------------------------------------------
      - addressable_rainbow:
          name: "Rainbow"
      - addressable_rainbow:
          name: "Fast Rainbow"
          speed: 50
          width: 25

      - addressable_color_wipe:
          name: "Color Wipe"
          add_led_interval: 50ms
      - addressable_color_wipe:
          name: "Red Green Wipe"
          add_led_interval: 100ms
          colors:
            # --- CORRECTED YAML SYNTAX START ---
            - red: 1.0
              green: 0.0
              blue: 0.0
              num_leds: 10
            - red: 0.0
              green: 1.0
              blue: 0.0
              num_leds: 10
            # --- CORRECTED YAML SYNTAX END ---

      - addressable_scan:
          name: "Scan"

      - addressable_twinkle:
          name: "Twinkle"
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_twinkle:
          name: "Slow Twinkle"
          twinkle_probability: 2%
          progress_interval: 32ms

      - addressable_random_twinkle:
          name: "Random Twinkle"

      - addressable_fireworks:
          name: "Fireworks"
      - addressable_fireworks:
          name: "Random Color Fireworks"
          use_random_color: true
          spark_probability: 5%
          fade_out_rate: 80

      - addressable_flicker:
          name: "Addressable Flicker"
          intensity: 10%

      - automation:
          name: "Automation RGB Cycle"
          sequence:
            - light.addressable_set:
                id: ws2812_strip
                range_from: 0
                range_to: ${num_leds}
                red: 1.0
                green: 0.0
                blue: 0.0
            - delay: 1s
            - light.addressable_set:
                id: ws2812_strip
                range_from: 0
                range_to: ${num_leds}
                red: 0.0
                green: 1.0
                blue: 0.0
            - delay: 1s
            - light.addressable_set:
                id: ws2812_strip
                range_from: 0
                range_to: ${num_leds}
                red: 0.0
                green: 0.0
                blue: 1.0
            - delay: 1s

